---
title: "Courses"
output: html_document
---

<style type="text/css">
h1 {
  font-size: 45px;
  text-align: center;
}
h1.title {
  font-size: 40px;
  text-align: center;
}
</style>

$$\\[0.1cm]$$

## Teaching

$$\\[0.1cm]$$

**Fundamentals of R (co-lecturered with Livio Silva-Muller)** 

*Fall 2022; Spring 2023; Fall 2023 (upcoming) at The Graduate Institute of International and Development Studies (IHEID)*

This course offers masters' students a hands on introduction to data science using the R programming language and software. We teach students how to import, transform, analyze, and visualize various types of data in R. To help students think through data, we show practical applications of R for the analysis of environment, finance, and conflict data.

$$\\[0.1cm]$$

**Intermediate R for Social Science Research**

*Fall 2023 (upcoming) at The Graduate Institute of International and Development Studies (IHEID)*

This course offers masters' students an applied overview of various research methods using R. Students learn how to write, cite, and include table and figures using R Markdown; how to select and carry-on different types of statistical modeling; how to work with unsupervised approaches for text analysis; and how to code, visualize, and model network data.

$$\\[0.1cm]$$

## Invited talks

$$\\[0.1cm]$$

**Anti-Political Correctness and Authenticity: Authenticity performances in politics in Brazil and the United States** 

Lecture for the Research Group on Elections and Political Citizenship (GREC) at the Université de Lausanne on 31 March 2022
